import React, { useState } from 'react';
import {
  FileText,
  Download,
  Printer,
  Copy,
  Check,
  X,
  Dna,
  Sparkles,
  CheckCircle2,
  Share2,
} from 'lucide-react';
import { ProteinData, MutationSimulation, AISynthesisReport } from '../../types';
import { buildFullResearchReport } from '../../services/evidenceRetrieverService';
import { downloadReportPdf } from '../../services/pdfReportGenerator';

interface ExportReportModalProps {
  protein: ProteinData;
  mutations: MutationSimulation[];
  aiReport: AISynthesisReport | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  protein,
  mutations,
  aiReport,
}) => {
  const [copied, setCopied] = useState(false);
  const [isExportingPdf, setIsExportingPdf] = useState(false);
  const [exportType, setExportType] = useState<'markdown' | 'json' | 'preview'>('preview');

  if (!isOpen) return null;

  const handleDownloadPdf = async () => {
    setIsExportingPdf(true);
    try {
      const fullReport = buildFullResearchReport(protein);
      await downloadReportPdf(fullReport, protein);
    } catch (err) {
      console.error('PDF export failed', err);
    } finally {
      setIsExportingPdf(false);
    }
  };

  const handlePrint = async () => {
    try {
      window.print();
    } catch (err) {
      console.warn('window.print() restricted, falling back to PDF download', err);
      await handleDownloadPdf();
    }
  };

  const generateMarkdown = () => {
    return `# PROTEOFLOW BIOINFORMATICS DOSSIER
**Generated by ProteoFlow Pipeline** • ${new Date().toUTCString()}

---

## 1. IDENTIFICATION & GENERAL METADATA
- **Name:** ${protein.name}
- **Symbol / Gene:** ${protein.gene || 'N/A'}
- **Accession / Primary ID:** ${protein.id}
- **UniProtKB Accession:** ${protein.uniprotId || 'N/A'}
- **RCSB PDB ID:** ${protein.pdbId || 'N/A'}
- **Organism:** ${protein.organism || 'Homo sapiens'}
- **Polypeptide Length:** ${protein.length} Amino Acids

---

## 2. PHYSICOCHEMICAL & PRIMARY STRUCTURE PROFILE
- **Molecular Weight:** ${protein.molecularWeight.toFixed(2)} kDa
- **Isoelectric Point (pI):** ${protein.isoelectricPoint.toFixed(2)} pH
- **Net Charge (pH 7.4):** ${protein.netChargePh74 > 0 ? `+${protein.netChargePh74.toFixed(2)}` : protein.netChargePh74.toFixed(2)} e
- **Hydrophobic Residue Ratio:** ${protein.hydrophobicRatio.toFixed(1)}%
- **Extinction Coefficient (ε280):** ${protein.extinctionCoeff.toLocaleString()} M⁻¹cm⁻¹
- **Secondary Structure (Chou-Fasman):** 
  - α-Helix: ${protein.secondaryStructure.helixPct}%
  - β-Strand: ${protein.secondaryStructure.sheetPct}%
  - Random Coil: ${protein.secondaryStructure.coilPct}%

---

## 3. PRIMARY SEQUENCE (FASTA)
\`\`\`fasta
>${protein.id} ${protein.name} [${protein.organism || 'Homo sapiens'}]
${protein.sequence}
\`\`\`

---

## 4. FUNCTIONAL DOMAIN ARCHITECTURE (Pfam / UniProt)
${
  protein.domains.length === 0
    ? '*No domain boundaries annotated.*'
    : protein.domains
        .map((d) => `- **${d.name}** [Residues ${d.start}–${d.end}]: ${d.description || ''}`)
        .join('\n')
}

---

## 5. CATALYTIC, ACTIVE & BINDING SITES
${
  protein.activeSites.length === 0
    ? '*No specific catalytic sites cataloged.*'
    : protein.activeSites
        .map(
          (s) =>
            `- Position **#${s.residueIndex}** (${s.residueName}): **[${s.type.toUpperCase()}]** — ${s.description}`
        )
        .join('\n')
}

---

## 6. IN SILICO MUTATION EXPERIMENTS (${mutations.length} Tested Variants)
${
  mutations.length === 0
    ? '*No in silico mutations tested during this session.*'
    : mutations
        .map(
          (m) => `### Variant: ${m.originalResidue}${m.position}${m.mutatedResidue}
- **Classification:** ${m.pathogenicityClassification} (Impact: ${m.functionalImpactScore}/100)
- **Predicted Stability:** ${m.predictedStability}
- **Δ Charge:** ${m.deltaCharge > 0 ? `+${m.deltaCharge}` : m.deltaCharge} e | **Δ Hydropathy:** ${m.deltaHydropathy}
- **Biophysical Mechanism:** ${m.mechanismExplanation}
${m.clinVarAssociation ? `- **Clinical Landmark:** ${m.clinVarAssociation}` : ''}
`
        )
        .join('\n')
}

---

## 7. GEMINI 3.8 BIOCHEMICAL SYNTHESIS & HYPOTHESIS
${
  !aiReport
    ? '*AI Synthesis has not been executed yet. Run Gemini Synthesis in the dashboard to populate.*'
    : `### Executive Biochemical Summary
${aiReport.executiveSummary}

### Structural-Functional Mechanism Hypothesis
${aiReport.structuralMechanismHypothesis}

### Predicted Pathogenic / Phenotypic Impact
${aiReport.variantPathogenicityImpact}

### Therapeutic & Engineering Perspectives
${aiReport.therapeuticOrBiotechImplications}

### Recommended Validation Steps
${(aiReport.keyRecommendations || []).map((r, i) => `${i + 1}. ${r}`).join('\n')}
`
}

---
*Report generated via ProteoFlow Bioinformatics System. Verified for research and academic exploration.*
`;
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ProteoFlow_${protein.id}_Report.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const bundle = {
      targetProtein: protein,
      simulatedVariants: mutations,
      aiSynthesis: aiReport,
      exportedAt: new Date().toISOString(),
      proteoFlowVersion: '2.4',
    };
    const blob = new Blob([JSON.stringify(bundle, null, 2)], {
      type: 'application/json;charset=utf-8;',
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ProteoFlow_${protein.id}_Bundle.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyText = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-md animate-in fade-in duration-200">
      <div className="flex max-h-[90vh] w-full max-w-4xl flex-col rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl overflow-hidden print:border-none print:shadow-none print:max-h-none print:w-full print:bg-white print:text-black">
        {/* Modal Header (hidden on print) */}
        <div className="flex items-center justify-between border-b border-slate-800/90 px-6 py-4 bg-slate-950/60 print:hidden">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-cyan-500/20 text-cyan-400 border border-cyan-500/30">
              <Download className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">
                Export Complete Bioinformatics Dossier
              </h3>
              <p className="text-xs text-slate-400">
                Bundles sequence, 3D coordinates, active sites, simulated mutations & AI synthesis
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Tab Selector & Actions Bar (hidden on print) */}
        <div className="flex items-center justify-between border-b border-slate-800 px-6 py-2.5 bg-slate-950/40 text-xs print:hidden">
          <div className="flex items-center gap-1 rounded-lg bg-slate-900 p-1 border border-slate-800 font-medium">
            <button
              onClick={() => setExportType('preview')}
              className={`rounded-md px-3 py-1 transition-all ${
                exportType === 'preview'
                  ? 'bg-cyan-500/20 text-cyan-300 font-semibold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Document Preview
            </button>
            <button
              onClick={() => setExportType('markdown')}
              className={`rounded-md px-3 py-1 transition-all ${
                exportType === 'markdown'
                  ? 'bg-cyan-500/20 text-cyan-300 font-semibold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Raw Markdown (.md)
            </button>
            <button
              onClick={() => setExportType('json')}
              className={`rounded-md px-3 py-1 transition-all ${
                exportType === 'json'
                  ? 'bg-cyan-500/20 text-cyan-300 font-semibold'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              JSON Machine Bundle
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="export-pdf-btn"
              onClick={handleDownloadPdf}
              disabled={isExportingPdf}
              className="flex items-center gap-1.5 rounded-lg border border-cyan-500/40 bg-gradient-to-r from-cyan-600 to-emerald-600 px-3 py-1.5 text-white font-medium hover:from-cyan-500 hover:to-emerald-500 shadow-xs transition-all cursor-pointer disabled:opacity-60"
              title="Download publication-grade vector PDF dossier"
            >
              {isExportingPdf ? (
                <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-white border-t-transparent" />
              ) : (
                <Download className="h-3.5 w-3.5" />
              )}
              <span>{isExportingPdf ? 'Exporting PDF...' : 'Download PDF'}</span>
            </button>
            <button
              id="export-copy-btn"
              onClick={handleCopyText}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-2.5 py-1.5 text-slate-300 hover:text-white hover:bg-slate-800 transition-all cursor-pointer"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Text'}</span>
            </button>
            <button
              id="export-print-btn"
              onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-900 px-2.5 py-1.5 text-slate-300 hover:text-white hover:bg-slate-800 transition-all cursor-pointer"
            >
              <Printer className="h-3.5 w-3.5" />
              <span>Print</span>
            </button>
          </div>
        </div>

        {/* Modal Body / Report View */}
        <div className="flex-1 overflow-y-auto p-6 bg-slate-950 font-sans print:p-0 print:bg-white print:text-black">
          {exportType === 'preview' && (
            <div className="space-y-6 max-w-3xl mx-auto print:max-w-none">
              {/* Document Banner */}
              <div className="border-b border-slate-800 pb-4 print:border-black">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Dna className="h-6 w-6 text-cyan-400 print:text-black" />
                    <span className="text-xl font-bold tracking-tight text-white print:text-black">
                      ProteoFlow Research Dossier
                    </span>
                  </div>
                  <span className="text-xs text-slate-400 font-mono print:text-gray-600">
                    {new Date().toLocaleDateString()}
                  </span>
                </div>
                <h2 className="text-lg font-bold text-cyan-400 mt-2 print:text-black">
                  {protein.name} ({protein.id})
                </h2>
                <p className="text-xs text-slate-400 print:text-gray-700">
                  Organism: {protein.organism || 'Homo sapiens'} • Length: {protein.length} AA • UniProt: {protein.uniprotId || 'N/A'} • PDB: {protein.pdbId || 'N/A'}
                </p>
              </div>

              {/* Physicochemical Summary Table */}
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 print:text-black mb-2">
                  Physicochemical Properties
                </h4>
                <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 text-xs">
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Molecular Weight</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      {protein.molecularWeight.toFixed(2)} kDa
                    </span>
                  </div>
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Isoelectric Point (pI)</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      {protein.isoelectricPoint.toFixed(2)} pH
                    </span>
                  </div>
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Net Charge (pH 7.4)</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      {protein.netChargePh74 > 0 ? `+${protein.netChargePh74.toFixed(1)}` : protein.netChargePh74.toFixed(1)} e
                    </span>
                  </div>
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Secondary Structure</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      α:{protein.secondaryStructure.helixPct}% | β:{protein.secondaryStructure.sheetPct}% | c:{protein.secondaryStructure.coilPct}%
                    </span>
                  </div>
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Extinction ε280</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      {protein.extinctionCoeff.toLocaleString()} M⁻¹cm⁻¹
                    </span>
                  </div>
                  <div className="rounded-lg border border-slate-800 p-2.5 bg-slate-900/60 print:bg-gray-50 print:border-gray-300">
                    <span className="text-[10px] text-slate-400 block uppercase">Hydrophobic Ratio</span>
                    <span className="font-mono font-bold text-slate-200 print:text-black">
                      {protein.hydrophobicRatio.toFixed(1)}%
                    </span>
                  </div>
                </div>
              </div>

              {/* Active & Catalytic Sites */}
              <div>
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 print:text-black mb-2">
                  Catalytic & Active Sites ({protein.activeSites.length})
                </h4>
                <div className="space-y-1.5 text-xs">
                  {protein.activeSites.map((s, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between rounded-lg border border-slate-800 p-2 bg-slate-900/40 print:bg-white print:border-gray-300"
                    >
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-bold text-rose-400 print:text-black">
                          #{s.residueIndex} {s.residueName}
                        </span>
                        <span className="text-slate-300 print:text-gray-800">{s.description}</span>
                      </div>
                      <span className="font-mono text-[10px] text-slate-400 print:text-gray-600 uppercase">
                        {s.type}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* In Silico Mutations Section */}
              {mutations.length > 0 && (
                <div>
                  <h4 className="text-xs font-bold uppercase tracking-wider text-slate-300 print:text-black mb-2">
                    In Silico Simulated Mutations ({mutations.length})
                  </h4>
                  <div className="space-y-2 text-xs">
                    {mutations.map((m) => (
                      <div
                        key={m.id}
                        className="rounded-lg border border-slate-800 p-3 bg-slate-900/40 print:bg-white print:border-gray-300"
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-mono font-bold text-rose-400 print:text-black">
                            {m.originalResidue}{m.position}{m.mutatedResidue}
                          </span>
                          <span className="font-semibold text-slate-300 print:text-gray-800">
                            {m.pathogenicityClassification} (Score: {m.functionalImpactScore}/100)
                          </span>
                        </div>
                        <p className="mt-1 text-[11px] text-slate-400 print:text-gray-700">
                          {m.mechanismExplanation}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* AI Synthesis Section */}
              {aiReport && (
                <div className="space-y-3">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-cyan-400 print:text-black">
                    Gemini 3.8 Biochemical Synthesis & Mechanism
                  </h4>
                  <div className="rounded-xl border border-slate-800 p-4 bg-slate-900/60 space-y-3 text-xs text-slate-200 print:bg-white print:border-gray-300 print:text-black">
                    <div>
                      <strong className="text-cyan-300 print:text-black block mb-1">
                        Executive Summary:
                      </strong>
                      <p className="whitespace-pre-line text-slate-300 print:text-gray-800">
                        {aiReport.executiveSummary}
                      </p>
                    </div>

                    <div>
                      <strong className="text-emerald-300 print:text-black block mb-1">
                        Structural Mechanism Hypothesis:
                      </strong>
                      <p className="whitespace-pre-line text-slate-300 print:text-gray-800">
                        {aiReport.structuralMechanismHypothesis}
                      </p>
                    </div>

                    <div>
                      <strong className="text-rose-300 print:text-black block mb-1">
                        Variant Pathogenicity Assessment:
                      </strong>
                      <p className="whitespace-pre-line text-slate-300 print:text-gray-800">
                        {aiReport.variantPathogenicityImpact}
                      </p>
                    </div>

                    <div>
                      <strong className="text-purple-300 print:text-black block mb-1">
                        Therapeutic & Engineering Implications:
                      </strong>
                      <p className="whitespace-pre-line text-slate-300 print:text-gray-800">
                        {aiReport.therapeuticOrBiotechImplications}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          )}

          {exportType === 'markdown' && (
            <pre className="rounded-xl border border-slate-800 bg-slate-900/80 p-4 font-mono text-xs text-slate-300 whitespace-pre-wrap select-all">
              {generateMarkdown()}
            </pre>
          )}

          {exportType === 'json' && (
            <pre className="rounded-xl border border-slate-800 bg-slate-900/80 p-4 font-mono text-xs text-emerald-400 whitespace-pre-wrap select-all">
              {JSON.stringify(
                {
                  protein,
                  mutations,
                  aiReport,
                  exportDate: new Date().toISOString(),
                },
                null,
                2
              )}
            </pre>
          )}
        </div>

        {/* Modal Footer (hidden on print) */}
        <div className="flex items-center justify-between border-t border-slate-800/90 px-6 py-3 bg-slate-950/60 print:hidden">
          <div className="flex items-center gap-2">
            <button
              id="download-markdown-btn"
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 rounded-lg bg-cyan-600 px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-cyan-500 transition-all shadow-xs"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download Markdown (.md)</span>
            </button>
            <button
              id="download-json-btn"
              onClick={handleDownloadJSON}
              className="flex items-center gap-1.5 rounded-lg border border-slate-700 bg-slate-800 px-3.5 py-1.5 text-xs font-medium text-slate-200 hover:bg-slate-700 transition-all"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download JSON</span>
            </button>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg border border-slate-800 px-3 py-1.5 text-xs text-slate-400 hover:text-white transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
