import React, { useState } from 'react';
import {
  Sparkles,
  Loader2,
  Check,
  Copy,
  Download,
  AlertCircle,
  RefreshCw,
  Send,
  FileText,
  ShieldCheck,
  CheckCircle2,
  X,
} from 'lucide-react';
import { ProteinData, MutationSimulation, AISynthesisReport } from '../../types';

interface AIReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  protein: ProteinData;
  mutations: MutationSimulation[];
  aiReport: AISynthesisReport | null;
  onSetAiReport: (report: AISynthesisReport) => void;
  onOpenExportModal: () => void;
}

export const AIReportModal: React.FC<AIReportModalProps> = ({
  isOpen,
  onClose,
  protein,
  mutations,
  aiReport,
  onSetAiReport,
  onOpenExportModal,
}) => {
  const [customPrompt, setCustomPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleGenerateReport = async (promptOverride?: string) => {
    setIsGenerating(true);
    setErrorMessage(null);

    try {
      const response = await fetch('/api/synthesize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          proteinData: protein,
          testedMutations: mutations,
          customPrompt: promptOverride !== undefined ? promptOverride : customPrompt,
        }),
      });

      if (!response.ok) {
        const errJson = await response.json().catch(() => ({}));
        throw new Error(errJson.error || `Server synthesis returned error (${response.status})`);
      }

      const reportData: AISynthesisReport = await response.json();
      reportData.generatedAt = new Date().toLocaleString();
      onSetAiReport(reportData);
    } catch (err: any) {
      console.error('Synthesis error:', err);
      setErrorMessage(err.message || 'Failed to synthesize report.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyMarkdown = () => {
    if (!aiReport) return;
    const text = `# PROTEIN BIOINFORMATICS REPORT: ${protein.name} (${protein.id})
Generated by ProteoFlow with Gemini 3.8 Flash (${aiReport.generatedAt || new Date().toISOString()})

## 1. Executive Biochemical Summary
${aiReport.executiveSummary}

## 2. Structural-Functional Mechanism Hypothesis
${aiReport.structuralMechanismHypothesis}

## 3. Predicted Phenotypic & Pathogenic Impact of Variants
${aiReport.variantPathogenicityImpact}

## 4. Therapeutic, Drug Discovery & Biotechnology Perspectives
${aiReport.therapeuticOrBiotechImplications}

## 5. Recommended Experimental Validations
${(aiReport.keyRecommendations || []).map((r, i) => `${i + 1}. ${r}`).join('\n')}
`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 p-4 backdrop-blur-md animate-in fade-in duration-200">
      <div className="flex max-h-[90vh] w-full max-w-4xl flex-col rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-slate-800/90 px-6 py-4 bg-slate-950/60">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-500/20 to-emerald-500/20 border border-cyan-500/30 text-cyan-400">
              <Sparkles className="h-4 w-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                Gemini 3.8 Biochemical Synthesis & Mechanism Hypothesis
              </h3>
              <p className="text-xs text-slate-400">
                Target: <strong className="text-slate-200">{protein.name}</strong> ({protein.id}) • {mutations.length} tested variants
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          {/* Custom Inquiry Prompt Bar */}
          <div className="rounded-xl border border-slate-800 bg-slate-950 p-3 space-y-2">
            <div className="flex items-center justify-between text-xs">
              <label htmlFor="custom-ai-prompt" className="font-semibold text-slate-300 flex items-center gap-1.5">
                <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
                Custom In Silico Inquiry (Optional focus area):
              </label>
              <span className="text-[11px] text-slate-400">
                e.g., "Analyze allosteric transitions" or "Evaluate drug-binding pocket druggability"
              </span>
            </div>

            <div className="flex gap-2">
              <input
                id="custom-ai-prompt"
                type="text"
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                placeholder="Ask specific biophysical or therapeutic question..."
                className="flex-1 rounded-xl border border-slate-800 bg-slate-900 px-3 py-2 text-xs text-slate-200 placeholder:text-slate-400 focus:border-cyan-500 focus:outline-none"
              />
              <button
                id="submit-ai-prompt-btn"
                onClick={() => handleGenerateReport()}
                disabled={isGenerating}
                className="flex items-center gap-1.5 rounded-xl bg-gradient-to-r from-cyan-600 to-emerald-600 px-4 py-2 text-xs font-semibold text-white hover:from-cyan-500 hover:to-emerald-500 disabled:opacity-50 transition-all shadow-sm"
              >
                {isGenerating ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Send className="h-3.5 w-3.5" />}
                <span>{aiReport ? 'Re-Synthesize' : 'Generate Synthesis'}</span>
              </button>
            </div>
          </div>

          {/* Loading State */}
          {isGenerating && (
            <div className="flex flex-col items-center justify-center p-12 text-center rounded-xl border border-slate-800 bg-slate-950/40">
              <Loader2 className="h-9 w-9 animate-spin text-cyan-400 mb-3" />
              <h4 className="text-sm font-bold text-slate-200">
                Synthesizing In Silico Biophysical Intelligence...
              </h4>
              <p className="text-xs text-slate-400 mt-1 max-w-md">
                Aggregating primary sequence metrics, Chou-Fasman secondary structural coordinates, active site geometries, and {mutations.length} tested point mutations via Gemini 3.8 Flash.
              </p>
            </div>
          )}

          {/* Error Message */}
          {errorMessage && (
            <div className="flex items-center gap-2.5 rounded-xl border border-rose-800/60 bg-rose-950/40 p-4 text-xs text-rose-300">
              <AlertCircle className="h-5 w-5 shrink-0 text-rose-400" />
              <div>
                <span className="font-bold">Synthesis Error: </span>
                {errorMessage}
              </div>
            </div>
          )}

          {/* Generated Report Content */}
          {aiReport && !isGenerating && (
            <div className="space-y-4 animate-in fade-in duration-300">
              {/* Section 1: Executive Biochemical Summary */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
                <div className="flex items-center gap-2 mb-2">
                  <div className="h-2 w-2 rounded-full bg-cyan-400" />
                  <h4 className="text-xs font-bold uppercase tracking-wider text-cyan-400">
                    1. Executive Biochemical Summary
                  </h4>
                </div>
                <div className="text-xs text-slate-200 leading-relaxed whitespace-pre-line">
                  {aiReport.executiveSummary}
                </div>
              </div>

              {/* Section 2: Structural-Functional Mechanism */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
                <div className="flex items-center gap-2 mb-2">
                  <div className="h-2 w-2 rounded-full bg-emerald-400" />
                  <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-400">
                    2. Structural-Functional Mechanism Hypothesis
                  </h4>
                </div>
                <div className="text-xs text-slate-200 leading-relaxed whitespace-pre-line">
                  {aiReport.structuralMechanismHypothesis}
                </div>
              </div>

              {/* Section 3: Variant Pathogenicity Impact */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
                <div className="flex items-center gap-2 mb-2">
                  <div className="h-2 w-2 rounded-full bg-rose-400" />
                  <h4 className="text-xs font-bold uppercase tracking-wider text-rose-400">
                    3. Predicted Pathogenic / Phenotypic Variant Impact
                  </h4>
                </div>
                <div className="text-xs text-slate-200 leading-relaxed whitespace-pre-line">
                  {aiReport.variantPathogenicityImpact}
                </div>
              </div>

              {/* Section 4: Therapeutic & Biotechnology Implications */}
              <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
                <div className="flex items-center gap-2 mb-2">
                  <div className="h-2 w-2 rounded-full bg-purple-400" />
                  <h4 className="text-xs font-bold uppercase tracking-wider text-purple-400">
                    4. Therapeutic Targeting & Protein Engineering Perspectives
                  </h4>
                </div>
                <div className="text-xs text-slate-200 leading-relaxed whitespace-pre-line">
                  {aiReport.therapeuticOrBiotechImplications}
                </div>
              </div>

              {/* Section 5: Key Recommendations */}
              {aiReport.keyRecommendations && aiReport.keyRecommendations.length > 0 && (
                <div className="rounded-xl border border-slate-800 bg-slate-950/80 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className="h-2 w-2 rounded-full bg-amber-400" />
                    <h4 className="text-xs font-bold uppercase tracking-wider text-amber-400">
                      5. Recommended In Vitro & In Silico Validation Steps
                    </h4>
                  </div>
                  <ul className="space-y-1.5 text-xs text-slate-200">
                    {aiReport.keyRecommendations.map((rec, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                        <span>{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}

          {/* Empty State prompt */}
          {!aiReport && !isGenerating && !errorMessage && (
            <div className="flex flex-col items-center justify-center p-12 text-center rounded-xl border border-dashed border-slate-800">
              <Sparkles className="h-10 w-10 text-cyan-400/80 mb-3" />
              <h4 className="text-sm font-bold text-slate-200">
                Ready to Synthesize Publication-Grade Report
              </h4>
              <p className="text-xs text-slate-400 mt-1 max-w-md">
                Click "Generate Synthesis" to trigger Gemini 3.8 Flash. The AI will evaluate physicochemical metrics, active site coordination, and tested variants to formulate deep mechanistic hypotheses.
              </p>
              <button
                id="generate-initial-report-btn"
                onClick={() => handleGenerateReport()}
                className="mt-4 flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-600 to-emerald-600 px-5 py-2.5 text-xs font-semibold text-white hover:from-cyan-500 hover:to-emerald-500 transition-all shadow-md"
              >
                <Sparkles className="h-4 w-4" />
                <span>Run Gemini Biochemical Synthesis</span>
              </button>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="flex items-center justify-between border-t border-slate-800/90 px-6 py-3 bg-slate-950/60">
          <div className="text-[11px] text-slate-400 font-mono">
            Powered by Google GenAI SDK (gemini-3.8-flash)
          </div>

          <div className="flex items-center gap-2">
            {aiReport && (
              <>
                <button
                  id="copy-markdown-btn"
                  onClick={handleCopyMarkdown}
                  className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white hover:bg-slate-900 transition-all"
                >
                  {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-slate-400" />}
                  <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
                </button>

                <button
                  id="modal-open-export-btn"
                  onClick={() => {
                    onClose();
                    onOpenExportModal();
                  }}
                  className="flex items-center gap-1.5 rounded-lg bg-cyan-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-cyan-500 transition-all"
                >
                  <Download className="h-3.5 w-3.5" />
                  <span>Full Export & Print</span>
                </button>
              </>
            )}

            <button
              onClick={onClose}
              className="rounded-lg border border-slate-800 px-3 py-1.5 text-xs font-medium text-slate-400 hover:text-white transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
